# Generated by Django 2.2.4 on 2019-10-05 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Lotação')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do processo')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eletronico.Departamento', verbose_name='Lotação')),
                ('investigados', models.ManyToManyField(related_name='investigados', to='eletronico.Pessoa')),
                ('stakeholders', models.ManyToManyField(related_name='stakeholders', to='eletronico.Pessoa', verbose_name='Interessados')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eletronico.Pessoa')),
                ('matricula', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=('eletronico.pessoa',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eletronico.Documento')),
                ('justificativa', models.CharField(max_length=50)),
            ],
            bases=('eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eletronico.Documento')),
                ('texto', models.CharField(max_length=100)),
            ],
            bases=('eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Saiu em')),
                ('chegada', models.DateTimeField(blank=True, null=True, verbose_name='Chegou em')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino', to='eletronico.Departamento', verbose_name='Para')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origem', to='eletronico.Departamento', verbose_name='Saindo de')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eletronico.Processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='responsavel',
            field=models.ManyToManyField(to='eletronico.Pessoa'),
        ),
        migrations.AddField(
            model_name='processo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criado_por', to='eletronico.Funcionario', verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eletronico.Documento')),
                ('send_date', models.DateField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eletronico.Departamento')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
            bases=('eletronico.documento',),
        ),
        migrations.AddField(
            model_name='documento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eletronico.Funcionario'),
        ),
    ]
